# Generated by Django 3.2.6 on 2021-08-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0003_album_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_photo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
